#pragma once

#include "kernel/utility/encryption/crc/crc32/crc32.hpp"
#include "kernel/utility/encryption/crc/crc32/bzip2.hpp"
#include "kernel/utility/encryption/crc/crc32/jamcrc.hpp"
#include "kernel/utility/encryption/crc/crc32/common.hpp"
#include "kernel/utility/encryption/crc/crc32/c.hpp"
#include "kernel/utility/encryption/crc/crc32/d.hpp"
#include "kernel/utility/encryption/crc/crc32/mpeg2.hpp"
#include "kernel/utility/encryption/crc/crc32/posix.hpp"
#include "kernel/utility/encryption/crc/crc32/q.hpp"
#include "kernel/utility/encryption/crc/crc32/sata.hpp"
#include "kernel/utility/encryption/crc/crc32/xfer.hpp"
#include "kernel/utility/encryption/crc/crc8/common.hpp"
#include "kernel/utility/encryption/crc/crc8/crc8.hpp"
#include "kernel/utility/encryption/crc/crc8/cdma2000.hpp"
#include "kernel/utility/encryption/crc/crc8/darc.hpp"
#include "kernel/utility/encryption/crc/crc8/dvbs2.hpp"
#include "kernel/utility/encryption/crc/crc8/ebu.hpp"
#include "kernel/utility/encryption/crc/crc8/icode.hpp"
#include "kernel/utility/encryption/crc/crc8/itu.hpp"
#include "kernel/utility/encryption/crc/crc8/maxim.hpp"
#include "kernel/utility/encryption/crc/crc8/rohc.hpp"
#include "kernel/utility/encryption/crc/crc8/wcdma.hpp"
#include "kernel/utility/encryption/crc/crc16/common.hpp"
#include "kernel/utility/encryption/crc/crc16/arc.hpp"
#include "kernel/utility/encryption/crc/crc16/augccitt.hpp"
#include "kernel/utility/encryption/crc/crc16/buypass.hpp"
#include "kernel/utility/encryption/crc/crc16/cdma2000.hpp"
#include "kernel/utility/encryption/crc/crc16/ccittfalse.hpp"
#include "kernel/utility/encryption/crc/crc16/dectr.hpp"
#include "kernel/utility/encryption/crc/crc16/dds110.hpp"
#include "kernel/utility/encryption/crc/crc16/dectx.hpp"
#include "kernel/utility/encryption/crc/crc16/dnp.hpp"
#include "kernel/utility/encryption/crc/crc16/en13757.hpp"
#include "kernel/utility/encryption/crc/crc16/genibus.hpp"
#include "kernel/utility/encryption/crc/crc16/t10dif.hpp"
#include "kernel/utility/encryption/crc/crc16/kermit.hpp"
#include "kernel/utility/encryption/crc/crc16/mcrf4xx.hpp"
#include "kernel/utility/encryption/crc/crc16/maxim.hpp"
#include "kernel/utility/encryption/crc/crc16/riello.hpp"
#include "kernel/utility/encryption/crc/crc16/tms37157.hpp"
#include "kernel/utility/encryption/crc/crc16/teledisk.hpp"
#include "kernel/utility/encryption/crc/crc16/modbus.hpp"
#include "kernel/utility/encryption/crc/crc16/x25.hpp"
#include "kernel/utility/encryption/crc/crc16/usb.hpp"
#include "kernel/utility/encryption/crc/crc16/xmodem.hpp"

namespace Sen::Kernel::Encryption::CRC {

}