// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARsR4UuC94Ulv0FxHltJtke5S5tod66gw',
    appId: '1:769586089598:android:4f297b607020f64192522f',
    messagingSenderId: '769586089598',
    projectId: 'sen-environment-ec078',
    storageBucket: 'sen-environment-ec078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyz3ICy-_YW3W-vdvMpugEhOqS3YM-MXk',
    appId: '1:769586089598:ios:99d455007ce03df292522f',
    messagingSenderId: '769586089598',
    projectId: 'sen-environment-ec078',
    storageBucket: 'sen-environment-ec078.firebasestorage.app',
    iosBundleId: 'com.haruma.sen.environment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyz3ICy-_YW3W-vdvMpugEhOqS3YM-MXk',
    appId: '1:769586089598:ios:99d455007ce03df292522f',
    messagingSenderId: '769586089598',
    projectId: 'sen-environment-ec078',
    storageBucket: 'sen-environment-ec078.firebasestorage.app',
    iosBundleId: 'com.haruma.sen.environment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhuexParHURlcL_TnFeLjXNYpLnF1h-Tk',
    appId: '1:769586089598:web:461ba9cbbdf804c692522f',
    messagingSenderId: '769586089598',
    projectId: 'sen-environment-ec078',
    authDomain: 'sen-environment-ec078.firebaseapp.com',
    storageBucket: 'sen-environment-ec078.firebasestorage.app',
    measurementId: 'G-E8F9S8WVYR',
  );
}
